version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    logging:
      driver: json-file

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: json-file

  ravendb:
    image: ravendb/ravendb
    environment:
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
    ports:
      - "8080:8080"
      - "38888:38888" # Port for server communication
    volumes:
      - ravendb-data:/opt/RavenDB/Server/RavenData
    logging:
      driver: json-file

volumes:
  ravendb-data:
